version: '3.7'
services:
  mongodb:
    image: mongo:4.0
    env_file: .env
    command: --wiredTigerCacheSizeGB $MONGO_CACHE_SIZE
    ports:
      - "$MONGO_PORT:27017"
    volumes:
      - $DATA_DIR:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}    
    restart: unless-stopped
    
  
  
  
  
       